# Generated by Django 3.2.15 on 2022-10-02 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug para las URLs de los proyectos')),
                ('nombre_proyecto', models.CharField(max_length=80, verbose_name='Nombre del proyecto')),
                ('descripcion_proyecto', models.TextField(verbose_name='Descripción del proyecto')),
                ('lenguajes_utilizados', models.CharField(help_text='Ejemplo: Python, Javascript, Ruby, etc.', max_length=80, verbose_name='Lenguajes utilizados en el proyecto')),
                ('bases_de_datos', models.CharField(help_text='Ejemplo: MySQL, PostgreSQL, MongoDB, etc.', max_length=80, verbose_name='Bases de datos utilizadas en el proyecto')),
                ('frameworks_backend', models.CharField(blank=True, help_text='Ejemplo: Django, Sails.js, Rails, etc.', max_length=80, verbose_name='Frameworks Backend utilizados en el proyecto (opcional)')),
                ('frameworks_frontend', models.CharField(blank=True, help_text='Ejemplo: Angular.js, Backbone.js, Bootstrap, etc.', max_length=80, verbose_name='Frameworks Frontend utilizados en el proyecto (opcional)')),
                ('servidor_web', models.CharField(blank=True, help_text='Ejemplo: Apache, Nginx, Unicorn, Tomcat, Gunicorn, etc.', max_length=50, verbose_name='Servidor web en el que corre el proyecto (opcional)')),
                ('plugins_libs', models.TextField(blank=True, help_text='Ejemplo: jQuery, React.js, Fancybox, jQuery UI, etc.', verbose_name='Plugins y librerías utilizadas en el proyecto (opcional)')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
