# Generated by Django 3.2.15 on 2022-10-02 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modulo', models.CharField(max_length=35, verbose_name='Nombre del módulo')),
                ('descripcion_modulo', models.TextField(verbose_name='Descripción del módulo')),
                ('nivel', models.PositiveSmallIntegerField(verbose_name='Nivel del módulo')),
                ('path', models.CharField(max_length=250, verbose_name='Ruta del módulo')),
                ('modulo_depende', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submodulos', to='documentacion.modulo')),
                ('modulo_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submodulos_totales', to='documentacion.modulo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPaquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_paquete', models.CharField(max_length=5, unique=True, verbose_name='Clave del paquete')),
                ('tipo_paquete', models.CharField(max_length=50, verbose_name='Tipo del paquete')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paquete', models.CharField(max_length=35, verbose_name='Nombre del paquete')),
                ('descripcion_paquete', models.TextField(blank=True, verbose_name='Descripción del paquete (opcional)')),
                ('path', models.CharField(blank=True, max_length=250, verbose_name='Ruta del paquete')),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes', to='documentacion.modulo')),
                ('paquetes_requeridos', models.ManyToManyField(related_name='paquetes_dependen', to='documentacion.Paquete')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='proyectos.proyecto')),
                ('tipo_paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='documentacion.tipopaquete')),
            ],
        ),
    ]
