# Generated by Django 3.2.15 on 2022-10-02 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=35, verbose_name='Campo de la tabla')),
                ('longitud', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Longitud del campo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción del campo')),
                ('campo_clave', models.BooleanField(verbose_name='Campo clave')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40, verbose_name='Tipo de dato')),
            ],
        ),
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tabla', models.CharField(max_length=35, verbose_name='Nombre de la tabla')),
                ('descripcion_tabla', models.CharField(max_length=150, verbose_name='Descripción de la tabla')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablas', to='proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='diccionario_de_datos.campo')),
                ('tabla_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='diccionario_de_datos.tabla')),
            ],
        ),
        migrations.AddField(
            model_name='campo',
            name='tabla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='diccionario_de_datos.tabla'),
        ),
        migrations.AddField(
            model_name='campo',
            name='tipo_dato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='diccionario_de_datos.tipodato'),
        ),
    ]
