# Generated by Django 3.2.15 on 2022-10-02 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proceso', models.CharField(max_length=50, verbose_name='Nombre del proceso')),
                ('descripcion_proceso', models.TextField(verbose_name='Descripción del proceso')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=50, verbose_name='Responsable involucrado en el proceso')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='procesos.proceso')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=150, verbose_name='Nombre de la actividad')),
                ('tipo_actividad', models.CharField(choices=[('E', 'Entrada'), ('P', 'Proceso'), ('D', 'Decisión'), ('S', 'Salida')], max_length=1, verbose_name='Tipo de actividad')),
                ('orden', models.PositiveSmallIntegerField()),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='procesos.proceso')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='procesos.responsable')),
            ],
        ),
    ]
